import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Navigation} from "@/app/components/Navigation";
import {PageFooter} from "@/app/components/PageFooter";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  

  return (
    <html lang="en">
    <body className={inter.className}>
    <Navigation></Navigation>
    {children}
    <PageFooter></PageFooter>
    </body>
    </html>
  )
}
